export const CREATE_NEW_BOARD = "CREATE_NEW_BOARD";
export const CANCEL_NEW_BOARD = "CANCEL_NEW_BOARD";
export const SUBMIT_NEW_BOARD = "SUBMIT_NEW_BOARD";
export const STORE_NEW_BOARD_TO_COLLECTION = "STORE_NEW_BOARD_TO_COLLECTION";
export const CREATE_UNTITLED_BOARD = "CREATE_UNTITLED_BOARD";